language: python
cache: pip
matrix:
    include:
        - python: 3.8
          env:
          arch: arm64
install:
    - sudo apt-get update
    # package reqs
    - pip install --upgrade pip
    - pip install pygam
    - pip install -r requirements.txt
    - pip install pandas

script:
    - py.test --cov=pygam

after_success:
    - codecov
    
